import React from "react";
import { motion } from "framer-motion";
import { 
    Compass, 
    BookOpen, 
    Key, 
    ListOrdered, 
    Timer,
    ArrowRightCircle 
} from "lucide-react";

void motion;

const StudyPathViewer = ({ studyPath, onClose }) => {
    const roadmap = studyPath.roadmap_json;

    return (
        <motion.div 
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            className="section-card"
            style={{ position: 'relative', overflow: 'hidden' }}
        >
            <button 
                onClick={onClose}
                style={{ 
                    position: 'absolute', 
                    top: '20px', 
                    right: '20px', 
                    background: '#f1f5f9', 
                    border: 'none', 
                    padding: '8px 16px', 
                    borderRadius: '8px', 
                    cursor: 'pointer',
                    fontWeight: '700'
                }}
            >
                Close
            </button>

            <div style={{ display: 'flex', alignItems: 'center', gap: '12px', marginBottom: '32px' }}>
                <div style={{ padding: '12px', background: '#0f172a', color: '#fff', borderRadius: '12px' }}>
                    <Compass size={24} />
                </div>
                <div>
                    <h2 style={{ margin: 0, fontSize: '24px', fontWeight: '800' }}>AI Study Roadmap</h2>
                    <p style={{ margin: 0, color: '#64748b', fontSize: '14px' }}>Generated by Orion-X AI</p>
                </div>
            </div>

            <div className="roadmap-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '32px' }}>
                <div className="left-col">
                    <section style={{ marginBottom: '32px' }}>
                        <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '18px', color: '#1e293b' }}>
                            <BookOpen size={18} /> Summary
                        </h3>
                        <p style={{ color: '#475569', lineHeight: '1.6', fontSize: '15px' }}>{roadmap.summary}</p>
                    </section>

                    <section>
                        <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '18px', color: '#1e293b' }}>
                            <Key size={18} /> Key Terms
                        </h3>
                        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '8px' }}>
                            {roadmap.key_terms.map((term, i) => (
                                <motion.span 
                                    initial={{ opacity: 0, scale: 0.8 }}
                                    animate={{ opacity: 1, scale: 1 }}
                                    transition={{ delay: i * 0.1 }}
                                    key={i} 
                                    style={{ 
                                        padding: '6px 14px', 
                                        background: '#f1f5f9', 
                                        borderRadius: '999px', 
                                        fontSize: '13px', 
                                        fontWeight: '600',
                                        color: '#334155'
                                    }}
                                >
                                    {term}
                                </motion.span>
                            ))}
                        </div>
                    </section>
                </div>

                <div className="right-col">
                    <section style={{ background: '#f8fafc', padding: '24px', borderRadius: '20px', border: '1px solid #f1f5f9' }}>
                        <h3 style={{ display: 'flex', alignItems: 'center', gap: '8px', fontSize: '18px', color: '#1e293b', marginTop: 0 }}>
                            <ListOrdered size={18} /> Suggested Reading Order
                        </h3>
                        <div style={{ display: 'grid', gap: '12px', marginTop: '16px' }}>
                            {roadmap.reading_order.map((step, i) => (
                                <motion.div 
                                    initial={{ opacity: 0, x: -10 }}
                                    animate={{ opacity: 1, x: 0 }}
                                    transition={{ delay: i * 0.15 }}
                                    key={i} 
                                    style={{ 
                                        display: 'flex', 
                                        alignItems: 'center', 
                                        gap: '12px', 
                                        padding: '12px', 
                                        background: '#fff', 
                                        borderRadius: '12px',
                                        boxShadow: '0 2px 4px rgba(0,0,0,0.02)'
                                    }}
                                >
                                    <ArrowRightCircle size={16} color="#3b82f6" />
                                    <span style={{ fontSize: '14px', fontWeight: '500', color: '#334155' }}>{step}</span>
                                </motion.div>
                            ))}
                        </div>
                        
                        <div style={{ marginTop: '24px', display: 'flex', alignItems: 'center', gap: '8px', color: '#64748b', fontSize: '14px', fontWeight: '600' }}>
                            <Timer size={16} />
                            <span>Estimated study time: {roadmap.estimated_time}</span>
                        </div>
                    </section>
                </div>
            </div>
        </motion.div>
    );
};

export default StudyPathViewer;
